### PR TITLE
Added app.js and data.JSON files

### PR DESCRIPTION
**Pull request by apurv789**
Following are the changes which I have made:

1. Removed blog-post-1.html to blog-post-7.html which were being used to render separate blog pages.
2. Instead, I have added a JSON file that stores some data related to all the blogs, and when the user clicks on a particular blog,
A single HTML file (blog-post.html) will be loaded each time, only the content displayed will differ.

Inked2_LI
Inked3_LI

### CODE REVIEW

**Comment by apurv789** [comment]
@pulkithanda let me know if there are other changes to make...

**Comment by apurv789** [comment]
Do you want me to add more blogs to the page??

**Comment by apurv789** [comment]
> @apurv789 The idea is no doubt nice but can you add some demo content to display this ?

I have added some images above, which reflect the changes i have made.

**Comment by pulkithanda** [comment]
Hey @apurv789 when i try to see the netlify deploy I can see only 1 repeated page and not different pages.

**Comment by apurv789** [comment]
> Hey @apurv789 when i try to see the netlify deploy I can see only 1 repeated page and not different pages.
Hey @pulkithanda when I see it on netlify deploy , it is working as expected. Here I am attaching a demo video for you to see.

https://user-images.githubusercontent.com/63352826/136908857-19b01368-a7ad-4f8b-b42e-f7e35e76e98c.mp4

**Pull request closed without merging**
